service: math-pyramid
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  region: eu-central-1

functions:
  math-pyramid:
    handler: src/math-pyramid-handler.createHandler
    events:
      - http:
          path: /create
          method: post
plugins:
  - serverless-offline
  - serverless-esbuild

