AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  math-pyramid

  Creates math pyramid data: size, solutionValues, startValues which can be used by an app to display the math pyramid.

Globals:
  Function:
    Timeout: 1
  # API is slow in our case (>1s) locally and when deployed. Using lambda function URL is much faster but has no local execution support.
  # URL for lambda invocation locally from app: 'curl -XPOST http://127.0.0.1:3001/2015-03-31/functions/MathPyramidFunction/invocations'
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Origin,X-Requested-With,Content-Type,Accept'"
      #AllowOrigin: "'http://127.0.0.1:3000'"
      AllowOrigin: "'*'"

Resources:
  MathPyramidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: math-pyramid/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      MemorySize: 128
      # FunctionUrlConfig: -> no local invocation support, but fast when deployed
      #   AuthType: NONE
      #   InvokeMode: BUFFERED
      #   Cors:
      #     AllowMethods:
      #       - GET
      #     AllowOrigins: 
      #       - '*'
      #     AllowHeaders:
      #     - 'Origin'
      #     - 'X-Requested-With'
      #     - 'Content-Type'
      Architectures:
        - x86_64
      Events:
        MathPyramid:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
          - app.ts

Outputs:
  MathPyramidFunction:
    Description: "MathPyramid Lambda Function ARN"
    Value: 
      Fn::GetAtt: MathPyramidFunction.Arn
  MathPyramidApi:
    Description: "API Gateway endpoint URL for Prod stage for MathPyramid function"
    Value: 
      !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create/"
  # MathPyramidUrlEndpoint:
  #     Description: "MathPyramid Lambda Function URL Endpoint"
  #     Value:
  #       Fn::GetAtt: MathPyramidFunctionUrl.FunctionUrl    
  MathPyramidFunctionIamRole:
    Description: "Implicit IAM Role created for MathPyramid function"
    Value: 
      Fn::GetAtt: MathPyramidFunctionRole.Arn
