AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  math-pyramid

  Sample SAM Template for math-pyramid

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Origin,X-Requested-With,Content-Type,Accept'"
      #AllowOrigin: "'http://127.0.0.1:3000'"
      AllowOrigin: "'*'"

Resources:
  MathPyramidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: math-pyramid/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      MemorySize: 128
      Architectures:
        - x86_64
      Events:
        MathPyramid:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MathPyramidApi:
    Description: "API Gateway endpoint URL for Prod stage for MathPyramid function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create/"
  MathPyramidFunction:
    Description: "MathPyramid Lambda Function ARN"
    Value: !GetAtt MathPyramidFunction.Arn
  MathPyramidFunctionIamRole:
    Description: "Implicit IAM Role created for MathPyramid function"
    Value: !GetAtt MathPyramidFunctionRole.Arn
