service: math-pyramid
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  region: eu-central-1
  logs:
    websocket:
      format: '{ "requestId":"$context.requestId",   "ip": "$context.identity.sourceIp" }'

functions:
  connectionHandler:
    handler: src/websocket/connection-handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: username
  defaultHandler:
    handler: src/websocket/default-handler.handler
    events:
      - websocket:
          route: $default #simple event definition without extra route property
  broadcastHandler:
    handler: src/websocket/broadcast-handler.handler
    events:
      - websocket:
          route: start # triggers if $request.body.action === "start"
      - websocket:
          route: message
custom:
  serverless-offline:
    httpPort: 3001
    websocketPort: 3002
    lambdaPort: 3003
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 3010
      inMemory: true
      docker: true
      migrate: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: players
        AttributeDefinitions:
          - AttributeName: connectionid
            AttributeType: S
        KeySchema:
          - AttributeName: connectionid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline
